//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ThermoCalc.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_THERMOCALC_FORM             101
#define IDR_MAINFRAME                   128
#define IDR_INPUTDLG                    129
#define IDR_OUTPUT                      130
#define IDD_PP_TAMP1                    136
#define IDD_PP_TAMP2                    138
#define MAINDLGCOPY                     141
#define IDD_ForCalcFlow_F               142
#define IDD_ForCalcFlow_IS              143
#define IDD_ForCalcFlow_EPS             144
#define IDD_ForCalcFlow_V               145
#define IDD_ForCalcFlow_Pa              150
#define ID_START_ID_O                   201
#define ID_START_ID_OP                  300
#define ID_START_ID_OENT                400
#define ID_START_ID_OSPIN               500
#define ID_UFX                          600
#define ID_ENT_UFX                      700
#define ID_START_ID_O_STEP              800
#define IDC_IO1                         1000
#define IDC_UXF                         1001
#define IDC_FUEL_UXF                    1001
#define IDC_BUTTON1                     1003
#define IDC_BUTTON2                     1004
#define IDC_FUEL_ENT2                   1005
#define IDC_SPIN1                       1006
#define IDC_BUTTON_CALC_UXF             1007
#define IDC_IOP1                        1008
#define IDC_BUTTON_CALC_SECTION         1008
#define IDC_BUTTON_CALCSECTION          1008
#define IDC_IO2                         1009
#define IDC_IOP2                        1010
#define IDC_IO3                         1011
#define IDC_IOP3                        1012
#define IDC_SPIN2                       1013
#define IDC_IO4                         1014
#define IDC_IOP4                        1015
#define IDC_IC1                         1016
#define IDC_ICP1                        1017
#define IDC_IC2                         1018
#define IDC_ICP2                        1019
#define IDC_IC3                         1020
#define IDC_ICI1                        1021
#define IDC_ICP3                        1022
#define IDC_ICI2                        1023
#define IDC_IC4                         1024
#define IDC_ICP4                        1025
#define IDC_ICI3                        1026
#define IDC_ICI24                       1027
#define IDC_Alfa                        1028
#define IDC_Temperature                 1029
#define IDC_Pressure                    1030
#define IDC_SPIN3                       1031
#define IDC_CHECK1                      1032
#define IDC_ICI4                        1038
#define IDC_ICI5                        1039
#define IDC_ICI6                        1040
#define IDC_CHECK_CALC_UXF              1043
#define IDC_CHECK_ATMOSPHERE_SECTION    1044
#define IDC_ButtonAppendFormulO         1045
#define IDC_ButtonDisFormulO            1046
#define IDC_CHECK_SECTION_PA2           1048
#define IDC_ButtonAppendPressure        1049
#define IDC_ButtonDisPressure           1050
#define IDC_CHECK_INCLUDE_CC            1051
#define IDC_ButtonAppendFormulC         1054
#define IDC_ButtonDisFormulC            1055
#define IDC_STATIC2                     1060
#define IDC_STATIC3                     1061
#define IDC_RICHEDIT1                   1063
#define IDC_ButtonAppendAlfa            1064
#define IDC_ButtonAppendAlfa2           1065
#define IDC_ButtonDisAlfa               1066
#define IDC_ButtonDisAlfa2              1067
#define IDC_EDIT1                       1071
#define IDC_RADIO1                      1074
#define IDC_RADIO2                      1075
#define IDC_CHECK_CRITIC_SECTION        1077
#define IDC_TemperatureMax              1078
#define IDC_TemperatureMin              1079
#define IDC_ButtonAppendPressureInSection 1100
#define IDC_ButtonDisPressureInSection  1101
#define IDC_ButtonAppendPowerExpNozzle  1102
#define IDC_ButtonDisPowerExpNozzle     1103
#define IDC_ButtonAppendIS              1104
#define IDC_ButtonDisIS                 1105
#define IDC_ButtonAppendV               1106
#define IDC_ButtonDisV                  1107
#define IDC_ButtonAppendEPS             1108
#define IDC_ButtonDisEPS                1109
#define IDC_ButtonValueIS               11010
#define IDC_ButtonStepIS                11011
#define ID_OUTPUT_FULL                  32771
#define ID_OUTPUT_SHORT                 32772
#define ID_VIEW_PRECISION               32774
#define ID_VIEW_ASTRAVIEW               32775
#define ID_VIEW_EXPONENTVIEW            32776
#define ID_VIEW_PARTIALPRESSURES        32778
#define ID_VIEW_MOLESFRACTION           32780
#define ID_FILE_OPEN_IN_EXCEL           32789
#define ID_INSERT_FORMULENTHALPY        32790
#define ID_INSERT_FORMUL_OX             32790
#define ID_INSERT_ALFA                  32791
#define ID_INSERTFIELDS_PRESSURE        32792
#define ID_INSERT_FORMUL_COMB           32793
#define ID_SAVEOPTIONS_S                32794
#define ID_FILE_SAVE_TEXT               32795
#define ID_LOADOPTIONS_LOADDATABASESONSTART 32796
#define ID_VIEW_SETUPTABSIZE            32797
#define ID_VIEW                         32798
#define ID_EXCELOPTIONS                 32799
#define ID_UNITMEASURE                  32802
#define ID_MINNAMESINOUTPUT             32803
#define ID_VIEW_OTHERVIEW               32804
#define IDS_STRING_ALFA                 61446

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        159
#define _APS_NEXT_COMMAND_VALUE         32805
#define _APS_NEXT_CONTROL_VALUE         1080
#define _APS_NEXT_SYMED_VALUE           112
#endif
#endif
