if(UNIX)
	set(XLS_PATH ${PROJECT_SOURCE_DIR}/../Libs/xlsxio)
	find_library(XLS_LIBRARY "libxlsxio_read.a" ${HINTS} PATHS ${XLS_PATH} NO_DEFAULT_PATH REQUIRED)
	add_library(xls STATIC IMPORTED )
	set_property(TARGET xls PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${XLS_PATH}/include)
	include_directories( ${XLS_PATH}/include )
else()
	set(XLS_PATH "$ENV{ProgramFiles}/xlsxio")
	find_library(XLS_LIBRARY "xlsxio_read.lib" PATHS "${XLS_PATH}/lib" NO_DEFAULT_PATH REQUIRED)
	add_library(xls STATIC IMPORTED )
	set_property(TARGET xls PROPERTY INTERFACE_INCLUDE_DIRECTORIES "${XLS_PATH}/include")
endif()

set_property(TARGET xls PROPERTY IMPORTED_LOCATION ${XLS_LIBRARY})
